# Generated by Django 5.0.6 on 2025-08-04 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='alumno',
            new_name='curso',
        ),
    ]
